live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 14.0
bold =        { family = "Firacode Nerd Font", style = "Bold"}
bold_italic = { family = "Firacode Nerd Font", style = "Bold Italic"}
italic =      { family = "Firacode Nerd Font", style = "Italic"}
normal =      { family = "Firacode Nerd Font", style = "Regular"}
offset =      { x = 0, y = 0}

[keyboard]
bindings = [
{ key = "H",      mods = "Alt|Option", action = "ReceiveChar" },
{ key = "L",      mods = "Alt|Option", action = "ReceiveChar" },
{ key = "U",      mods = "Control|Shift", action = "Paste" },
{ key = "V",      mods = "Control|Shift", action = "PasteSelection" },
{ key = "C",      mods = "Control|Shift", action = "Copy" },
{ key = "N",      mods = "Control|Shift", action = "SpawnNewInstance" },
{ key = "Return", mods = "Control",       action = "ToggleFullScreen" },
{ key = "Key0",   mods = "Control",       action = "ResetFontSize" },
{ key = "Equals", mods = "Control",       action = "IncreaseFontSize" },
{ key = "Minus",  mods = "Control",       action = "DecreaseFontSize" },
]
[mouse]
bindings = [
{ mouse = "Middle", mods = "Shift", action = "PasteSelection" },
{ mouse = "Right", mods = "Shift", action = "ExpandSelection" },
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.985
# option_as_alt = "Both"
padding = { x = 5, y = 5}
dimensions = { columns = 140, lines = 72}
