# .bashrc
# Source Silicon Team bashrc
if [ -f /opt/tools/bin/silicon_team_bashrc ]; then
#  . /opt/tools/bin/silicon_team_bashrc
   . /etc/bashrc
elif [ -f /etc/bashrc ]; then # look for system bashrc if we dont find the silicon team file
   . /etc/bashrc
fi

# User customization starts here
source ~/corp_settings.sh 2>/dev/null || echo "Attention: setup ~/corp_settings.sh" 
source ~/dotfiles/bash_functions.sh
source ~/dotfiles/bash_aliases.sh

# Sensible cli setup
if [[ $- == *i* ]]; then
   stty sane
   set -o vi
   set -o physical
   set t_Co=256
   umask 002
   shopt -s cdspell
   shopt -s histappend
   shopt -s cdable_vars
   shopt -s autocd
   shopt -s direxpand
   bind '"\e[A": history-search-backward'  # sane arrow keys
   bind '"\e[B": history-search-forward'
   bind '"\e[C": forward-char'
   bind '"\e[D": backward-char'
fi

export HISTCONTROL="erasedups:ignoredups" HISTSIZE=1000000 HISTFILESIZE=1000000000 HISTIGNORE='pwd:exit:fg:bg:top:clear:history:ls:ll:uptime:df'
export EDITOR=vim
export IGNOREEOF=1 # use exit to leave shell
export CDPATH+=.:

# temp modpath
modpath ~/arm-tools/xpacks/.bin b
modpath ~/.local/arm-tools/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin b
modpath ~/.local/nvim-macos/bin b
modpath /opt/tools/bin a
modpath /opt/si/emu/users/soummya/tools/ads/bin b
modpath /opt/tools/qnx/7.1/host/linux/x86_64/usr/bin a
