# .bashrc
source /usr/share/lsf/conf/profile.lsf 2>/dev/null
source ~/corp_settings.sh
source ~/dotfiles/bash_functions.sh
source ~/dotfiles/bash_aliases.sh

# Sensible cli setup
if [[ $- == *i* ]]; then
   stty sane
   set -o vi
   set -o physical
   set t_Co=256
   umask 002
   shopt -s cdspell
   shopt -s histappend
   shopt -s cdable_vars
   shopt -s autocd
   shopt -s direxpand
   bind '"\e[A": history-search-backward'  # sane arrow keys
   bind '"\e[B": history-search-forward'
   bind '"\e[C": forward-char'
   bind '"\e[D": backward-char'
fi

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=100000
export HISTFILESIZE=100000
export HISTTIMEFORMAT="[%h-%d %T] "
export HISTIGNORE='pwd:exit:fg:bg:top:c:clear::b:.:..:...:....:z:h:history:ls:ll:ld'

export EDITOR=nvim
export IGNOREEOF=1 # use exit to leave shell
export CDPATH+=.:
