os:
  edit: 'zvim {{filename}}'
  editAtLine: 'zvim --line={{line}} {{filename}}'
  copyToClipboardCmd: 'xclip'
gui:
  nerdFontsVersion: "3"
  refreshInterval: 20000
git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never
  autoFetch: true
  CommitMessage: "TOk-1123:"
  fetchInterval: 300
keybinding:
  commits:
    amendCommit: ["A"]
    rewordCommit: ["R"]
