os:
  edit: 'zvim {{filename}}'
  editAtLine: 'zvim --line={{line}} {{filename}}'
  copyToClipboardCmd: 'xclip'
gui:
  nerdFontsVersion: "3"
git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never
